# Generated by Django 4.0.4 on 2022-06-03 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0002_book_account_avatar_ganre'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ganre',
            new_name='Genre',
        ),
    ]
