# Generated by Django 4.0.4 on 2022-06-07 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0007_alter_rate_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='list_read_book',
            field=models.ManyToManyField(to='UserApp.book', verbose_name='Прочитанные книги'),
        ),
    ]
