# Generated by Django 4.0.4 on 2022-06-07 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0009_alter_rate_book_alter_rate_rate_alter_rate_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rate',
            old_name='user',
            new_name='account',
        ),
        migrations.AlterUniqueTogether(
            name='rate',
            unique_together={('account', 'book')},
        ),
    ]
